edition = "2021"
version = "Two"
unstable_features = true
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Item"
imports_layout = "HorizontalVertical"
indent_style = "Block"
max_width = 100
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true
